import { CLAUDE_CODE_IDENTITY, CLAUDE_CODE_IDENTITY_PATTERN, PI_HARNESS_IDENTITY_PATTERN, PI_IDENTITY_SENTENCE_PATTERN, PI_REMOVAL_ANCHORS } from "./constants.js";

export function sanitiseSystemPrompt(raw: string): string {
  const paragraphs = raw.split(/\n\n+/);
  const filtered = paragraphs.filter((p) =>
    !PI_REMOVAL_ANCHORS.some((anchor) => p.includes(anchor)),
  );

  return filtered
    .join("\n\n")
    .replace(CLAUDE_CODE_IDENTITY_PATTERN, "")
    .replace(PI_IDENTITY_SENTENCE_PATTERN, "")
    .replace(PI_HARNESS_IDENTITY_PATTERN, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

interface SystemTextBlock {
  type: string;
  text?: unknown;
  [key: string]: unknown;
}

function isPiClaudeCodeIdentityBlock(block: unknown): block is SystemTextBlock {
  if (!block || typeof block !== "object") return false;
  const candidate = block as SystemTextBlock;
  return candidate.type === "text"
    && typeof candidate.text === "string"
    && candidate.text.trim() === CLAUDE_CODE_IDENTITY;
}

/**
 * Sanitise the host prompt in the exact Anthropic OAuth shape generated by the
 * current pi-ai runtime: the Claude Code identity is the first system block.
 * Looking only at that exact first block avoids treating a later user-authored
 * identity mention as proof of OAuth. The runtime remains solely responsible
 * for inserting the initial identity and selecting OAuth headers. Later system
 * updates are sanitised too and repeat the identity alongside their instructions.
 */
export function sanitiseAnthropicPayloadSystem(payload: unknown): unknown {
  if (!payload || typeof payload !== "object") return payload;
  const system = (payload as { system?: unknown }).system;
  if (!Array.isArray(system) || !isPiClaudeCodeIdentityBlock(system[0])) return payload;

  let changed = false;
  const newSystem: unknown[] = [system[0]];
  for (let i = 1; i < system.length; i++) {
    const block = system[i];
    if (
      block && typeof block === "object"
      && (block as SystemTextBlock).type === "text"
      && typeof (block as SystemTextBlock).text === "string"
    ) {
      const original = (block as SystemTextBlock).text as string;
      const sanitised = sanitiseSystemPrompt(original);
      if (sanitised !== original) changed = true;
      if (sanitised) newSystem.push({ ...block, text: sanitised });
      else changed = true;
    } else {
      newSystem.push(block);
    }
  }

  // Pi 0.86+ can send prompt updates as system messages in the transcript.
  // Only transform their text; tool additions/removals and conversation content
  // must remain unchanged. Keep the OAuth guard above for every transformation.
  const messages = (payload as { messages?: unknown }).messages;
  const newMessages = Array.isArray(messages) ? messages.map((message: unknown) => {
    if (!message || typeof message !== "object") return message;
    const candidate = message as { role?: unknown; content?: unknown };
    if (candidate.role !== "system") return message;

    if (typeof candidate.content === "string") {
      const cleaned = sanitiseSystemPrompt(candidate.content);
      const content = cleaned ? `${CLAUDE_CODE_IDENTITY}\n\n${cleaned}` : CLAUDE_CODE_IDENTITY;
      if (content === candidate.content) return message;
      changed = true;
      return { ...message, content };
    }
    if (!Array.isArray(candidate.content)) return message;

    let messageChanged = false;
    let hasIdentity = false;
    const content = candidate.content.map((block: unknown) => {
      if (!block || typeof block !== "object") return block;
      const textBlock = block as SystemTextBlock;
      if (textBlock.type !== "text" || typeof textBlock.text !== "string") return block;
      const cleaned = sanitiseSystemPrompt(textBlock.text);
      const text = hasIdentity ? cleaned
        : cleaned ? `${CLAUDE_CODE_IDENTITY}\n\n${cleaned}` : CLAUDE_CODE_IDENTITY;
      hasIdentity = true;
      if (text === textBlock.text) return block;
      messageChanged = true;
      return { ...textBlock, text };
    }).filter((block: unknown) => {
      if (!block || typeof block !== "object") return true;
      const candidate = block as SystemTextBlock;
      return candidate.type !== "text" || candidate.text !== "";
    });
    if (!messageChanged) return message;
    changed = true;
    return { ...message, content };
  }) : undefined;

  return changed ? {
    ...payload,
    system: newSystem,
    ...(newMessages ? { messages: newMessages } : {}),
  } : payload;
}
