import { CLAUDE_CODE_IDENTITY, CLAUDE_CODE_IDENTITY_PATTERN, PI_HARNESS_IDENTITY_PATTERN, PI_IDENTITY_SENTENCE_PATTERN, PI_REMOVAL_ANCHORS } from "./constants.js";

export function sanitiseSystemPrompt(raw: string): string {
  const paragraphs = raw.split(/\n\n+/);
  const filtered = paragraphs.filter((p) =>
    !PI_REMOVAL_ANCHORS.some((anchor) => p.includes(anchor)),
  );

  return filtered
    .join("\n\n")
    .replace(CLAUDE_CODE_IDENTITY_PATTERN, "")
    .replace(PI_IDENTITY_SENTENCE_PATTERN, "")
    .replace(PI_HARNESS_IDENTITY_PATTERN, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

interface SystemTextBlock {
  type: string;
  text?: unknown;
  [key: string]: unknown;
}

function isPiClaudeCodeIdentityBlock(block: unknown): block is SystemTextBlock {
  if (!block || typeof block !== "object") return false;
  const candidate = block as SystemTextBlock;
  return candidate.type === "text"
    && typeof candidate.text === "string"
    && candidate.text.trim() === CLAUDE_CODE_IDENTITY;
}

/**
 * Sanitise the host prompt in the exact Anthropic OAuth shape generated by the
 * current pi-ai runtime: the Claude Code identity is the first system block.
 * Looking only at that exact first block avoids treating a later user-authored
 * identity mention as proof of OAuth. The runtime remains solely responsible
 * for inserting the identity and selecting OAuth headers.
 */
export function sanitiseAnthropicPayloadSystem(payload: unknown): unknown {
  if (!payload || typeof payload !== "object") return payload;
  const system = (payload as { system?: unknown }).system;
  if (!Array.isArray(system) || !isPiClaudeCodeIdentityBlock(system[0])) return payload;

  let changed = false;
  const newSystem: unknown[] = [system[0]];
  for (let i = 1; i < system.length; i++) {
    const block = system[i];
    if (
      block && typeof block === "object"
      && (block as SystemTextBlock).type === "text"
      && typeof (block as SystemTextBlock).text === "string"
    ) {
      const original = (block as SystemTextBlock).text as string;
      const sanitised = sanitiseSystemPrompt(original);
      if (sanitised !== original) changed = true;
      if (sanitised) newSystem.push({ ...block, text: sanitised });
      else changed = true;
    } else {
      newSystem.push(block);
    }
  }

  return changed ? { ...payload, system: newSystem } : payload;
}
